import * as kv from "./kv_store.tsx";

// Helper function to create reliable Unsplash URLs
function getUnsplashUrl(photoId: string, width = 500, height = 500): string {
  return `https://images.unsplash.com/${photoId}?auto=format&fit=crop&w=${width}&h=${height}&q=80`;
}

// Seed 50 products to the database
export async function seedProducts() {
  const products = [
    // ==================== ELEKTRONIK (8 produk) ====================
    {
      id: 'prod-001',
      name: 'Earbuds Bluetooth TWS Premium',
      slug: 'earbuds-bluetooth-tws-premium',
      description: 'Earbuds wireless dengan kualitas suara jernih, battery life 24 jam, dan charging case yang compact. Dilengkapi dengan noise cancellation untuk pengalaman mendengarkan yang optimal.',
      price: 299000,
      originalPrice: 450000,
      discount: 34,
      stock: 150,
      category: 'Elektronik',
      images: [getUnsplashUrl('photo-1590658268037-6bf12165a8df')],
      rating: 4.8,
      reviewCount: 1240,
      sold: 3450,
      isActive: true,
      createdAt: new Date('2024-01-15').toISOString(),
    },
    {
      id: 'prod-002',
      name: 'Smartwatch Fitness Tracker Pro',
      slug: 'smartwatch-fitness-tracker-pro',
      description: 'Smartwatch dengan fitur fitness tracking lengkap, heart rate monitor, sleep tracking, dan water resistant hingga 50m. Baterai tahan hingga 7 hari.',
      price: 850000,
      originalPrice: 1200000,
      discount: 29,
      stock: 85,
      category: 'Elektronik',
      images: [getUnsplashUrl('photo-1579586337278-3befd40fd17a')],
      rating: 4.7,
      reviewCount: 892,
      sold: 2150,
      isActive: true,
      createdAt: new Date('2024-01-18').toISOString(),
    },
    {
      id: 'prod-003',
      name: 'Power Bank Fast Charging 20000mAh',
      slug: 'power-bank-fast-charging-20000mah',
      description: 'Power bank kapasitas besar dengan teknologi fast charging PD 20W. Dapat mengisi daya 3 device sekaligus dengan aman dan cepat.',
      price: 175000,
      stock: 230,
      category: 'Elektronik',
      images: [getUnsplashUrl('photo-1609091839311-d5365f9ff1c5')],
      rating: 4.6,
      reviewCount: 1580,
      sold: 5200,
      isActive: true,
      createdAt: new Date('2024-01-20').toISOString(),
    },
    {
      id: 'prod-004',
      name: 'Charger Fast Charging 65W GaN',
      slug: 'charger-fast-charging-65w-gan',
      description: 'Charger kompak dengan teknologi GaN untuk pengisian super cepat. Kompatibel dengan laptop, smartphone, dan tablet. 3 port USB untuk multitasking.',
      price: 245000,
      originalPrice: 350000,
      discount: 30,
      stock: 120,
      category: 'Elektronik',
      images: [getUnsplashUrl('photo-1625948515291-69613efd103f')],
      rating: 4.9,
      reviewCount: 765,
      sold: 1890,
      isActive: true,
      createdAt: new Date('2024-01-22').toISOString(),
    },
    {
      id: 'prod-005',
      name: 'Headphone Over-Ear Wireless',
      slug: 'headphone-over-ear-wireless',
      description: 'Headphone premium dengan active noise cancellation, bass yang powerful, dan kenyamanan maksimal untuk penggunaan jangka panjang. Baterai 30 jam.',
      price: 675000,
      originalPrice: 950000,
      discount: 29,
      stock: 65,
      category: 'Elektronik',
      images: [getUnsplashUrl('photo-1546435770-a3e426bf472b')],
      rating: 4.8,
      reviewCount: 634,
      sold: 1250,
      isActive: true,
      createdAt: new Date('2024-01-25').toISOString(),
    },
    {
      id: 'prod-006',
      name: 'Speaker Portable Bluetooth Waterproof',
      slug: 'speaker-portable-bluetooth-waterproof',
      description: 'Speaker portable dengan suara 360 derajat, waterproof IPX7, dan baterai tahan 12 jam. Cocok untuk outdoor dan indoor.',
      price: 425000,
      stock: 95,
      category: 'Elektronik',
      images: [getUnsplashUrl('photo-1608043152269-423dbba4e7e1')],
      rating: 4.7,
      reviewCount: 891,
      sold: 2340,
      isActive: true,
      createdAt: new Date('2024-01-28').toISOString(),
    },
    {
      id: 'prod-007',
      name: 'Lampu LED Pintar RGB WiFi',
      slug: 'lampu-led-pintar-rgb-wifi',
      description: 'Lampu LED smart dengan 16 juta warna, kontrol via smartphone, dan kompatibel dengan Google Home & Alexa. Hemat energi hingga 80%.',
      price: 135000,
      originalPrice: 200000,
      discount: 33,
      stock: 180,
      category: 'Elektronik',
      images: [getUnsplashUrl('photo-1558618666-fcd25c85cd64')],
      rating: 4.5,
      reviewCount: 1120,
      sold: 3780,
      isActive: true,
      createdAt: new Date('2024-02-01').toISOString(),
    },
    {
      id: 'prod-008',
      name: 'Webcam Full HD 1080p Pro',
      slug: 'webcam-full-hd-1080p-pro',
      description: 'Webcam berkualitas tinggi untuk meeting online, streaming, dan content creation. Auto focus, low light correction, dan built-in microphone.',
      price: 385000,
      stock: 75,
      category: 'Elektronik',
      images: [getUnsplashUrl('photo-1587825140708-dfaf72ae4b04')],
      rating: 4.7,
      reviewCount: 542,
      sold: 980,
      isActive: true,
      createdAt: new Date('2024-02-03').toISOString(),
    },

    // ==================== FASHION (8 produk) ====================
    {
      id: 'prod-009',
      name: 'Kemeja Pria Slim Fit Premium',
      slug: 'kemeja-pria-slim-fit-premium',
      description: 'Kemeja formal slim fit dengan bahan katun berkualitas tinggi. Nyaman dipakai seharian, anti kusut, dan tersedia berbagai warna.',
      price: 145000,
      originalPrice: 220000,
      discount: 34,
      stock: 200,
      category: 'Fashion',
      images: [getUnsplashUrl('photo-1602810318383-e386cc2a3ccf')],
      rating: 4.6,
      reviewCount: 1450,
      sold: 4200,
      isActive: true,
      createdAt: new Date('2024-01-16').toISOString(),
    },
    {
      id: 'prod-010',
      name: 'Dress Wanita Casual Elegant',
      slug: 'dress-wanita-casual-elegant',
      description: 'Dress casual dengan design modern dan elegant. Bahan adem, cocok untuk hangout atau acara semi formal. All size fit to L.',
      price: 189000,
      stock: 150,
      category: 'Fashion',
      images: [getUnsplashUrl('photo-1595777457583-95e059d581b8')],
      rating: 4.8,
      reviewCount: 2340,
      sold: 6750,
      isActive: true,
      createdAt: new Date('2024-01-19').toISOString(),
    },
    {
      id: 'prod-011',
      name: 'Jaket Hoodie Unisex Premium',
      slug: 'jaket-hoodie-unisex-premium',
      description: 'Hoodie premium dengan bahan fleece tebal dan lembut. Tersedia berbagai warna dan ukuran. Cocok untuk santai atau olahraga ringan.',
      price: 225000,
      originalPrice: 320000,
      discount: 30,
      stock: 175,
      category: 'Fashion',
      images: [getUnsplashUrl('photo-1556821840-3a63f95609a7')],
      rating: 4.7,
      reviewCount: 1890,
      sold: 5100,
      isActive: true,
      createdAt: new Date('2024-01-21').toISOString(),
    },
    {
      id: 'prod-012',
      name: 'Sepatu Sneakers Casual Sport',
      slug: 'sepatu-sneakers-casual-sport',
      description: 'Sneakers stylish dengan sol empuk dan breathable. Cocok untuk aktivitas sehari-hari, olahraga ringan, atau jalan-jalan.',
      price: 285000,
      stock: 110,
      category: 'Fashion',
      images: [getUnsplashUrl('photo-1549298916-b41d501d3772')],
      rating: 4.6,
      reviewCount: 1120,
      sold: 3200,
      isActive: true,
      createdAt: new Date('2024-01-24').toISOString(),
    },
    {
      id: 'prod-013',
      name: 'Tas Selempang Kulit Sintetis',
      slug: 'tas-selempang-kulit-sintetis',
      description: 'Tas selempang stylish dengan bahan kulit sintetis berkualitas. Banyak sekat, cocok untuk daily use, kuliah, atau kerja.',
      price: 165000,
      originalPrice: 250000,
      discount: 34,
      stock: 140,
      category: 'Fashion',
      images: [getUnsplashUrl('photo-1548036328-c9fa89d128fa')],
      rating: 4.7,
      reviewCount: 980,
      sold: 2890,
      isActive: true,
      createdAt: new Date('2024-01-27').toISOString(),
    },
    {
      id: 'prod-014',
      name: 'Hijab Premium Voal Ultrafine',
      slug: 'hijab-premium-voal-ultrafine',
      description: 'Hijab segiempat dengan bahan voal ultrafine yang adem, ringan, dan tidak menerawang. Tersedia 20+ pilihan warna cantik.',
      price: 45000,
      stock: 350,
      category: 'Fashion',
      images: [getUnsplashUrl('photo-1583846112902-820273e4143b')],
      rating: 4.9,
      reviewCount: 3450,
      sold: 12500,
      isActive: true,
      createdAt: new Date('2024-01-30').toISOString(),
    },
    {
      id: 'prod-015',
      name: 'Jam Tangan Fashion Analog',
      slug: 'jam-tangan-fashion-analog',
      description: 'Jam tangan fashion dengan design minimalis dan elegant. Tali kulit premium, waterproof, dan cocok untuk pria maupun wanita.',
      price: 195000,
      originalPrice: 280000,
      discount: 30,
      stock: 90,
      category: 'Fashion',
      images: [getUnsplashUrl('photo-1523275335684-37898b6baf30')],
      rating: 4.5,
      reviewCount: 876,
      sold: 2100,
      isActive: true,
      createdAt: new Date('2024-02-02').toISOString(),
    },
    {
      id: 'prod-016',
      name: 'Kaos Polos Cotton Combed 30s',
      slug: 'kaos-polos-cotton-combed-30s',
      description: 'Kaos polos premium dengan bahan cotton combed 30s. Adem, lembut, tidak berbulu. Tersedia 15 warna dan semua ukuran.',
      price: 55000,
      stock: 500,
      category: 'Fashion',
      images: [getUnsplashUrl('photo-1521572163474-6864f9cf17ab')],
      rating: 4.8,
      reviewCount: 5670,
      sold: 18900,
      isActive: true,
      createdAt: new Date('2024-02-05').toISOString(),
    },

    // ==================== MAKANAN (7 produk) ====================
    {
      id: 'prod-017',
      name: 'Kopi Arabika Bubuk Premium 250gr',
      slug: 'kopi-arabika-bubuk-premium-250gr',
      description: 'Kopi arabika pilihan dari dataran tinggi Gayo. Aroma harum, rasa smooth, dan tingkat keasaman seimbang. Roasted to perfection.',
      price: 85000,
      originalPrice: 120000,
      discount: 29,
      stock: 180,
      category: 'Makanan',
      images: [getUnsplashUrl('photo-1559056199-641a0ac8b55e')],
      rating: 4.9,
      reviewCount: 2340,
      sold: 7800,
      isActive: true,
      createdAt: new Date('2024-01-17').toISOString(),
    },
    {
      id: 'prod-018',
      name: 'Teh Hijau Premium Organik 100gr',
      slug: 'teh-hijau-premium-organik-100gr',
      description: 'Teh hijau organik kaya antioksidan. Membantu metabolisme, detoksifikasi, dan menjaga kesehatan. Tanpa pestisida.',
      price: 75000,
      stock: 220,
      category: 'Makanan',
      images: [getUnsplashUrl('photo-1564890369478-c89ca6d9cde9')],
      rating: 4.7,
      reviewCount: 1560,
      sold: 4200,
      isActive: true,
      createdAt: new Date('2024-01-20').toISOString(),
    },
    {
      id: 'prod-019',
      name: 'Cokelat Dark Chocolate 70% Kakao',
      slug: 'cokelat-dark-chocolate-70-kakao',
      description: 'Dark chocolate premium dengan 70% kakao murni. Kaya antioksidan, rendah gula, dan cocok untuk diet sehat. Kemasan 200gr.',
      price: 95000,
      originalPrice: 130000,
      discount: 27,
      stock: 150,
      category: 'Makanan',
      images: [getUnsplashUrl('photo-1511381939415-e44015466834')],
      rating: 4.8,
      reviewCount: 890,
      sold: 2450,
      isActive: true,
      createdAt: new Date('2024-01-23').toISOString(),
    },
    {
      id: 'prod-020',
      name: 'Keripik Kentang Pedas Manis 150gr',
      slug: 'keripik-kentang-pedas-manis-150gr',
      description: 'Snack keripik kentang dengan rasa pedas manis yang unik dan nagih. Renyah, gurih, dan cocok untuk segala suasana.',
      price: 25000,
      stock: 400,
      category: 'Makanan',
      images: [getUnsplashUrl('photo-1566478989037-eec170784d0b')],
      rating: 4.6,
      reviewCount: 3200,
      sold: 15600,
      isActive: true,
      createdAt: new Date('2024-01-26').toISOString(),
    },
    {
      id: 'prod-021',
      name: 'Madu Murni Hutan Premium 500ml',
      slug: 'madu-murni-hutan-premium-500ml',
      description: 'Madu murni 100% dari hutan Indonesia. Kaya nutrisi, membantu daya tahan tubuh, dan cocok untuk konsumsi keluarga.',
      price: 145000,
      stock: 95,
      category: 'Makanan',
      images: [getUnsplashUrl('photo-1587049352846-4a222e784056')],
      rating: 4.9,
      reviewCount: 1780,
      sold: 4500,
      isActive: true,
      createdAt: new Date('2024-01-29').toISOString(),
    },
    {
      id: 'prod-022',
      name: 'Sambal Botol Pedas Nikmat 250ml',
      slug: 'sambal-botol-pedas-nikmat-250ml',
      description: 'Sambal pedas dengan bahan pilihan dan resep tradisional. Tingkat kepedasan sedang, cocok untuk teman makan apa saja.',
      price: 35000,
      stock: 300,
      category: 'Makanan',
      images: [getUnsplashUrl('photo-1626967685074-46e2831bb6e4')],
      rating: 4.7,
      reviewCount: 2450,
      sold: 8900,
      isActive: true,
      createdAt: new Date('2024-02-01').toISOString(),
    },
    {
      id: 'prod-023',
      name: 'Granola Sehat Mix Nuts 300gr',
      slug: 'granola-sehat-mix-nuts-300gr',
      description: 'Granola sehat dengan campuran oats, nuts, dan dried fruits. Cocok untuk sarapan, snack sehat, atau topping yogurt.',
      price: 65000,
      originalPrice: 90000,
      discount: 28,
      stock: 160,
      category: 'Makanan',
      images: [getUnsplashUrl('photo-1600716051809-e997e11a5d52')],
      rating: 4.8,
      reviewCount: 1120,
      sold: 3400,
      isActive: true,
      createdAt: new Date('2024-02-04').toISOString(),
    },

    // ==================== KESEHATAN (7 produk) ====================
    {
      id: 'prod-024',
      name: 'Masker Medis 3 Ply Earloop 50 pcs',
      slug: 'masker-medis-3-ply-earloop-50-pcs',
      description: 'Masker medis 3 lapis dengan filter berkualitas. Nyaman dipakai, breathable, dan melindungi dari debu, bakteri, dan polusi.',
      price: 45000,
      stock: 500,
      category: 'Kesehatan',
      images: [getUnsplashUrl('photo-1584634731339-252c581abfc5')],
      rating: 4.7,
      reviewCount: 4560,
      sold: 23400,
      isActive: true,
      createdAt: new Date('2024-01-18').toISOString(),
    },
    {
      id: 'prod-025',
      name: 'Vitamin C 1000mg Effervescent',
      slug: 'vitamin-c-1000mg-effervescent',
      description: 'Suplemen vitamin C dosis tinggi dalam bentuk tablet effervescent. Meningkatkan daya tahan tubuh dan antioksidan. Rasa jeruk segar.',
      price: 85000,
      originalPrice: 120000,
      discount: 29,
      stock: 220,
      category: 'Kesehatan',
      images: [getUnsplashUrl('photo-1584308666744-24d5c474f2ae')],
      rating: 4.8,
      reviewCount: 1890,
      sold: 5600,
      isActive: true,
      createdAt: new Date('2024-01-21').toISOString(),
    },
    {
      id: 'prod-026',
      name: 'Suplemen Herbal Multivitamin',
      slug: 'suplemen-herbal-multivitamin',
      description: 'Multivitamin dengan ekstrak herbal alami. Meningkatkan stamina, daya tahan tubuh, dan vitalitas. Aman untuk konsumsi harian.',
      price: 125000,
      stock: 150,
      category: 'Kesehatan',
      images: [getUnsplashUrl('photo-1550572017-4e6c8b68e342')],
      rating: 4.6,
      reviewCount: 1230,
      sold: 3780,
      isActive: true,
      createdAt: new Date('2024-01-24').toISOString(),
    },
    {
      id: 'prod-027',
      name: 'Termometer Digital Infrared',
      slug: 'termometer-digital-infrared',
      description: 'Termometer digital non-contact dengan sensor infrared akurat. Hasil cepat 1 detik, cocok untuk keluarga dan bayi.',
      price: 175000,
      originalPrice: 250000,
      discount: 30,
      stock: 85,
      category: 'Kesehatan',
      images: [getUnsplashUrl('photo-1584515933487-779824d29309')],
      rating: 4.7,
      reviewCount: 876,
      sold: 2100,
      isActive: true,
      createdAt: new Date('2024-01-27').toISOString(),
    },
    {
      id: 'prod-028',
      name: 'Alat Tensi Darah Digital',
      slug: 'alat-tensi-darah-digital',
      description: 'Tensimeter digital otomatis dengan layar LCD besar. Mudah digunakan, akurat, dan dilengkapi memory untuk tracking kesehatan.',
      price: 285000,
      stock: 75,
      category: 'Kesehatan',
      images: [getUnsplashUrl('photo-1615486511262-2d97f0f12b88')],
      rating: 4.8,
      reviewCount: 654,
      sold: 1560,
      isActive: true,
      createdAt: new Date('2024-01-30').toISOString(),
    },
    {
      id: 'prod-029',
      name: 'Hand Sanitizer Gel 500ml',
      slug: 'hand-sanitizer-gel-500ml',
      description: 'Hand sanitizer dengan alkohol 70%, membunuh 99.9% kuman dan bakteri. Formula lembut, tidak membuat tangan kering.',
      price: 35000,
      stock: 350,
      category: 'Kesehatan',
      images: [getUnsplashUrl('photo-1584799235813-aaf50827c6de')],
      rating: 4.6,
      reviewCount: 3450,
      sold: 15700,
      isActive: true,
      createdAt: new Date('2024-02-02').toISOString(),
    },
    {
      id: 'prod-030',
      name: 'Koyo Panas Pereda Nyeri Otot',
      slug: 'koyo-panas-pereda-nyeri-otot',
      description: 'Koyo panas untuk meredakan nyeri otot, pegal-pegal, dan kram. Efek hangat tahan lama 8 jam. Isi 10 lembar.',
      price: 25000,
      stock: 280,
      category: 'Kesehatan',
      images: [getUnsplashUrl('photo-1587854692152-cbe660dbde88')],
      rating: 4.5,
      reviewCount: 2340,
      sold: 8900,
      isActive: true,
      createdAt: new Date('2024-02-05').toISOString(),
    },

    // ==================== RUMAH TANGGA (7 produk) ====================
    {
      id: 'prod-031',
      name: 'Set Alat Masak Anti Lengket 7 pcs',
      slug: 'set-alat-masak-anti-lengket-7-pcs',
      description: 'Set peralatan masak lengkap dengan lapisan anti lengket premium. Tahan panas, mudah dibersihkan, dan hemat minyak.',
      price: 385000,
      originalPrice: 550000,
      discount: 30,
      stock: 65,
      category: 'Rumah Tangga',
      images: [getUnsplashUrl('photo-1565183997392-2f6f122e5912')],
      rating: 4.8,
      reviewCount: 890,
      sold: 2450,
      isActive: true,
      createdAt: new Date('2024-01-19').toISOString(),
    },
    {
      id: 'prod-032',
      name: 'Karpet Lantai Bulu Lembut 150x200cm',
      slug: 'karpet-lantai-bulu-lembut-150x200cm',
      description: 'Karpet berbulu halus dan lembut. Anti slip, mudah dibersihkan, dan cocok untuk ruang tamu atau kamar tidur. Tersedia 8 warna.',
      price: 245000,
      stock: 95,
      category: 'Rumah Tangga',
      images: [getUnsplashUrl('photo-1584502501508-3b4f8a3b5e33')],
      rating: 4.7,
      reviewCount: 1120,
      sold: 3200,
      isActive: true,
      createdAt: new Date('2024-01-22').toISOString(),
    },
    {
      id: 'prod-033',
      name: 'Lampu Meja Belajar LED Fleksibel',
      slug: 'lampu-meja-belajar-led-fleksibel',
      description: 'Lampu meja dengan leher fleksibel, 3 mode cahaya, dan brightness control. Hemat energi, cocok untuk belajar atau bekerja.',
      price: 125000,
      originalPrice: 180000,
      discount: 31,
      stock: 140,
      category: 'Rumah Tangga',
      images: [getUnsplashUrl('photo-1565881509155-23a4a25b9ebb')],
      rating: 4.6,
      reviewCount: 1560,
      sold: 4500,
      isActive: true,
      createdAt: new Date('2024-01-25').toISOString(),
    },
    {
      id: 'prod-034',
      name: 'Rak Penyimpanan Serbaguna 5 Susun',
      slug: 'rak-penyimpanan-serbaguna-5-susun',
      description: 'Rak plastik kokoh 5 tingkat untuk penyimpanan berbagai barang. Mudah dirakit, tidak mudah rusak, dan menghemat ruangan.',
      price: 195000,
      stock: 110,
      category: 'Rumah Tangga',
      images: [getUnsplashUrl('photo-1595428774223-ef52624120d2')],
      rating: 4.7,
      reviewCount: 2340,
      sold: 6700,
      isActive: true,
      createdAt: new Date('2024-01-28').toISOString(),
    },
    {
      id: 'prod-035',
      name: 'Sprei Katun Jepang King Size',
      slug: 'sprei-katun-jepang-king-size',
      description: 'Sprei set lengkap dengan bahan katun jepang premium. Adem, lembut, tidak luntur, dan awet. Motif modern elegan.',
      price: 275000,
      originalPrice: 380000,
      discount: 28,
      stock: 85,
      category: 'Rumah Tangga',
      images: [getUnsplashUrl('photo-1522771739844-6a9f6d5f14af')],
      rating: 4.8,
      reviewCount: 1890,
      sold: 5400,
      isActive: true,
      createdAt: new Date('2024-01-31').toISOString(),
    },
    {
      id: 'prod-036',
      name: 'Dispenser Air Hot & Cool',
      slug: 'dispenser-air-hot-cool',
      description: 'Dispenser dengan fitur hot & cool, hemat energi, dan safety lock untuk air panas. Cocok untuk rumah dan kantor.',
      price: 675000,
      stock: 45,
      category: 'Rumah Tangga',
      images: [getUnsplashUrl('photo-1625772452859-1c03d5bf1137')],
      rating: 4.6,
      reviewCount: 567,
      sold: 1230,
      isActive: true,
      createdAt: new Date('2024-02-03').toISOString(),
    },
    {
      id: 'prod-037',
      name: 'Set Gelas Kaca Premium 6 pcs',
      slug: 'set-gelas-kaca-premium-6-pcs',
      description: 'Set gelas kaca dengan design elegant dan modern. Kuat, jernih, dan cocok untuk berbagai minuman. Dishwasher safe.',
      price: 95000,
      stock: 150,
      category: 'Rumah Tangga',
      images: [getUnsplashUrl('photo-1571943899298-5b2a1d628f48')],
      rating: 4.7,
      reviewCount: 890,
      sold: 2890,
      isActive: true,
      createdAt: new Date('2024-02-06').toISOString(),
    },

    // ==================== OLAHRAGA (7 produk) ====================
    {
      id: 'prod-038',
      name: 'Dumbbell Set 5kg Pair',
      slug: 'dumbbell-set-5kg-pair',
      description: 'Dumbbell dengan coating vinyl anti slip. Cocok untuk home workout, membentuk otot lengan dan dada. Sepasang 2x5kg.',
      price: 185000,
      originalPrice: 260000,
      discount: 29,
      stock: 120,
      category: 'Olahraga',
      images: [getUnsplashUrl('photo-1571902943202-507ec2618e8f')],
      rating: 4.7,
      reviewCount: 1230,
      sold: 3450,
      isActive: true,
      createdAt: new Date('2024-01-20').toISOString(),
    },
    {
      id: 'prod-039',
      name: 'Matras Yoga Anti Slip Premium',
      slug: 'matras-yoga-anti-slip-premium',
      description: 'Matras yoga tebal 8mm dengan permukaan anti slip. Nyaman, tahan lama, dan dilengkapi tas untuk kemudahan membawa.',
      price: 145000,
      stock: 175,
      category: 'Olahraga',
      images: [getUnsplashUrl('photo-1592432678016-e910b452f9a2')],
      rating: 4.8,
      reviewCount: 2100,
      sold: 6700,
      isActive: true,
      createdAt: new Date('2024-01-23').toISOString(),
    },
    {
      id: 'prod-040',
      name: 'Bola Sepak Original Size 5',
      slug: 'bola-sepak-original-size-5',
      description: 'Bola sepak size 5 standar internasional. Kualitas premium, tahan lama, dan cocok untuk latihan atau pertandingan.',
      price: 125000,
      stock: 95,
      category: 'Olahraga',
      images: [getUnsplashUrl('photo-1614632537423-1e6c2e7e0aae')],
      rating: 4.6,
      reviewCount: 890,
      sold: 2340,
      isActive: true,
      createdAt: new Date('2024-01-26').toISOString(),
    },
    {
      id: 'prod-041',
      name: 'Raket Badminton Carbon Pro',
      slug: 'raket-badminton-carbon-pro',
      description: 'Raket badminton berbahan carbon fiber ringan namun kuat. Balance point sempurna untuk smash dan kontrol bola.',
      price: 285000,
      originalPrice: 400000,
      discount: 29,
      stock: 75,
      category: 'Olahraga',
      images: [getUnsplashUrl('photo-1626224583764-f87db24ac4ea')],
      rating: 4.8,
      reviewCount: 765,
      sold: 2100,
      isActive: true,
      createdAt: new Date('2024-01-29').toISOString(),
    },
    {
      id: 'prod-042',
      name: 'Botol Minum Sport 1 Liter',
      slug: 'botol-minum-sport-1-liter',
      description: 'Botol minum dengan kapasitas 1L, BPA free, anti tumpah, dan dilengkap tali. Cocok untuk gym, jogging, atau hiking.',
      price: 55000,
      stock: 280,
      category: 'Olahraga',
      images: [getUnsplashUrl('photo-1602143407151-7111542de6e8')],
      rating: 4.7,
      reviewCount: 3450,
      sold: 12300,
      isActive: true,
      createdAt: new Date('2024-02-01').toISOString(),
    },
    {
      id: 'prod-043',
      name: 'Treadmill Mini Foldable',
      slug: 'treadmill-mini-foldable',
      description: 'Treadmill kompak yang bisa dilipat, cocok untuk apartemen. LCD display untuk tracking speed, time, dan calories.',
      price: 1850000,
      originalPrice: 2500000,
      discount: 26,
      stock: 25,
      category: 'Olahraga',
      images: [getUnsplashUrl('photo-1576678927484-cc907957088c')],
      rating: 4.6,
      reviewCount: 234,
      sold: 450,
      isActive: true,
      createdAt: new Date('2024-02-04').toISOString(),
    },
    {
      id: 'prod-044',
      name: 'Resistance Band Set 5 Level',
      slug: 'resistance-band-set-5-level',
      description: 'Set resistance band dengan 5 tingkat resistance berbeda. Cocok untuk workout seluruh tubuh, portabel, dan hemat ruang.',
      price: 95000,
      stock: 200,
      category: 'Olahraga',
      images: [getUnsplashUrl('photo-1598289431512-b97b0917affc')],
      rating: 4.7,
      reviewCount: 1560,
      sold: 4890,
      isActive: true,
      createdAt: new Date('2024-02-07').toISOString(),
    },

    // ==================== BUKU (6 produk) ====================
    {
      id: 'prod-045',
      name: 'Buku Atomic Habits (Terjemahan)',
      slug: 'buku-atomic-habits-terjemahan',
      description: 'Buku pengembangan diri best seller karya James Clear. Panduan praktis membangun kebiasaan baik dan menghilangkan kebiasaan buruk.',
      price: 85000,
      originalPrice: 120000,
      discount: 29,
      stock: 150,
      category: 'Buku',
      images: [getUnsplashUrl('photo-1544947950-fa07a98d237f')],
      rating: 4.9,
      reviewCount: 3450,
      sold: 12500,
      isActive: true,
      createdAt: new Date('2024-01-21').toISOString(),
    },
    {
      id: 'prod-046',
      name: 'Novel Laskar Pelangi - Andrea Hirata',
      slug: 'novel-laskar-pelangi-andrea-hirata',
      description: 'Novel fiksi Indonesia yang menginspirasi tentang perjuangan anak-anak Belitung mengejar pendidikan. Wajib dibaca!',
      price: 75000,
      stock: 200,
      category: 'Buku',
      images: [getUnsplashUrl('photo-1512820790803-83ca734da794')],
      rating: 4.8,
      reviewCount: 4560,
      sold: 15600,
      isActive: true,
      createdAt: new Date('2024-01-24').toISOString(),
    },
    {
      id: 'prod-047',
      name: 'Buku Rich Dad Poor Dad (Terjemahan)',
      slug: 'buku-rich-dad-poor-dad-terjemahan',
      description: 'Buku bisnis dan keuangan klasik karya Robert Kiyosaki. Mengajarkan cara pandang berbeda tentang uang dan investasi.',
      price: 95000,
      originalPrice: 130000,
      discount: 27,
      stock: 130,
      category: 'Buku',
      images: [getUnsplashUrl('photo-1553729459-efe14ef6055d')],
      rating: 4.9,
      reviewCount: 2890,
      sold: 9800,
      isActive: true,
      createdAt: new Date('2024-01-27').toISOString(),
    },
    {
      id: 'prod-048',
      name: 'Buku Pendidikan Matematika SD Kelas 5',
      slug: 'buku-pendidikan-matematika-sd-kelas-5',
      description: 'Buku panduan belajar matematika untuk SD kelas 5. Lengkap dengan latihan soal dan pembahasan yang mudah dipahami.',
      price: 55000,
      stock: 180,
      category: 'Buku',
      images: [getUnsplashUrl('photo-1509021436665-8f07dbf5bf1d')],
      rating: 4.7,
      reviewCount: 1230,
      sold: 4500,
      isActive: true,
      createdAt: new Date('2024-01-30').toISOString(),
    },
    {
      id: 'prod-049',
      name: 'Buku Cerita Anak Dongeng Nusantara',
      slug: 'buku-cerita-anak-dongeng-nusantara',
      description: 'Kumpulan dongeng dari berbagai daerah di Indonesia. Full color illustration, cocok untuk anak usia 5-10 tahun.',
      price: 65000,
      stock: 220,
      category: 'Buku',
      images: [getUnsplashUrl('photo-1516979187457-637abb4f9353')],
      rating: 4.8,
      reviewCount: 2340,
      sold: 8900,
      isActive: true,
      createdAt: new Date('2024-02-02').toISOString(),
    },
    {
      id: 'prod-050',
      name: 'Komik Naruto Vol 1-5 (Set)',
      slug: 'komik-naruto-vol-1-5-set',
      description: 'Set komik Naruto volume 1 sampai 5. Kondisi baru, kertas berkualitas, dan terjemahan resmi Bahasa Indonesia.',
      price: 225000,
      originalPrice: 300000,
      discount: 25,
      stock: 75,
      category: 'Buku',
      images: [getUnsplashUrl('photo-1588497859490-85d1c17db96d')],
      rating: 4.9,
      reviewCount: 1890,
      sold: 5600,
      isActive: true,
      createdAt: new Date('2024-02-05').toISOString(),
    },
  ];

  // Check if products already exist (skip seeding if already seeded)
  try {
    const existingProduct = await kv.get('product:prod-001');
    if (existingProduct) {
      console.log(`ℹ️  Products already seeded (${products.length} products), skipping...`);
      return { success: true, count: products.length, skipped: true };
    }
  } catch (checkError: any) {
    console.log('⚠️  Could not check existing products, proceeding with seeding...');
  }

  // Insert all products into KV store with error handling
  let successCount = 0;
  let failCount = 0;
  
  for (const product of products) {
    try {
      await kv.set(`product:${product.id}`, product);
      successCount++;
    } catch (error: any) {
      console.error(`❌ Failed to seed product ${product.id}:`, error.message);
      failCount++;
      
      // If we have too many failures, stop early
      if (failCount > 5) {
        console.error(`❌ Too many failures (${failCount}), stopping seed process`);
        throw new Error(`Failed to seed products: ${failCount} failures out of ${successCount + failCount} attempts`);
      }
    }
  }

  console.log(`✅ Successfully seeded ${successCount} products (${failCount} failed)`);
  return { success: true, count: successCount, failed: failCount };
}